### ISSUE TITLE
Communication with the child process was ended,assertion failed error  Even reinstall

### ISSUE THREAD

**Issue by ann1111** [NativeScript/sidekick-feedback#233]
Hi Guys,

        Urgent I got this error
I have reinstall it still its shows in windows can you share me its solution ASAP

![img_18072018_163332_0](https://user-images.githubusercontent.com/12736476/42882508-b86a62cc-8ab6-11e8-8880-993083a681e5.png)

**Comment by ventsislav-georgiev** [comment]
@ann1111 Do you happen to use Node `10.6.0`? As the issue seem related to: https://github.com/NativeScript/sidekick-feedback/issues/227

**Comment by ann1111** [comment]
@ventsislav-georgiev Yes I use Node 10.6 let me check and revert back to you

**Comment by fontchastick** [comment]
same problem on Windows 10, 
node 10.6
nativescript 4.1.2

those are the main errors: 
  -assertion failed: frame_header.payload_length == sizeof xfer_info
  -file src\win\pipe.c, line 1709
 
and here the logs:
[console_18-07-19_17-32-59.796.log](https://github.com/NativeScript/sidekick-feedback/files/2210590/console_18-07-19_17-32-59.796.log)
[main_18-07-19_17-33-01.803.log](https://github.com/NativeScript/sidekick-feedback/files/2210591/main_18-07-19_17-33-01.803.log)

plz help! thx

**Comment by fontchastick** [comment]
i'm very thankfull to both of you @thewebkit and @ventsislav-georgiev 

you were right. as i dowgraded my node to 10.5 the bug was fixed

thank you so much guys!!!!

**Comment by ann1111** [comment]
Yes me too I downgrade it's working but build still not made from it checking that thanks

@thewebkit  @ventsislav-georgiev

**Comment by thewebkit** [comment]
@ann1111 

My nativescript projects are still in development so I haven't tried building the app for good, but for now i'm using the "Run on device" function (with local build) to an android smartphone connected to the computer, and it's working smoothly.

What build are you trying to make (ios or android ?) and what error do you get from it ?

**Comment by ann1111** [comment]
it gives me this error @thewebkit 

![image](https://user-images.githubusercontent.com/12736476/43005214-cbcb979c-8c4f-11e8-8c46-7eee0b8dca7e.png)

**Comment by thewebkit** [comment]
@ann1111 

I've just tried to build using the same settings as you (local build, with debug), and it worked (node 10.5.0). I'm using a Javascript template tho.

What version of node did you use to develop your app in the first place ? 
Did you switch from another version to the (former) latest 10.6.0 ?
I think the best thing to do would be downgrading back to the node version that worked for your previous build. Also posting the full logs of this new error my help other understand your problem and help you out !

**Comment by ann1111** [comment]
Yes its working fine after downgrading thanks
